# Generated by Django 3.2 on 2022-10-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20221024_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
