# Generated by Django 3.2 on 2022-10-28 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0005_auto_20221028_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_playlist', to='auth.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_subject', to='lessons.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='classe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='class_subject', to='lessons.class', verbose_name='Classes'),
            preserve_default=False,
        ),
    ]
